# This is a basic workflow to help you get started with Actions

name: Exemplo com docker e java

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-docker-js:
    runs-on: ubuntu-latest

    steps:
      -  name: Checkout do c√≥digo
         uses: actions/checkout@v4

      - name: Contruir imagem docker
        run: docker build -t meu-node-app .

      - name: executar container
        run: docker run meu-node-app
